import Link from 'next/link'
import {notFound} from 'next/navigation'
import {getProgramAdminById} from '../../../../lib/data'
import {getContentType} from '../../../../lib/content-types'
import {updateProgram,deleteProgram,createModule,updateModule,deleteModule,createLesson,updateLesson,deleteLesson,createMaterial,updateMaterial,deleteMaterial} from '../actions'

function localDateTime(value){if(!value)return'';const d=new Date(value);if(Number.isNaN(d.getTime()))return'';const pad=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`}
function childStatusLabel(value){return value==='published'?'Publicado':'Rascunho'}

export default async function ProgramAdminPage({params,searchParams}){
 const {id}=await params;const qs=await searchParams;const data=await getProgramAdminById(id);if(!data)notFound()
 const {program,modules,lessons,materials,enrollment_count}=data
 const lessonsByModule=new Map();for(const l of lessons){if(!lessonsByModule.has(l.module_id))lessonsByModule.set(l.module_id,[]);lessonsByModule.get(l.module_id).push(l)}
 const type=getContentType(program.content_type)
 const ok=qs?.saved||qs?.created||qs?.module_created||qs?.module_saved||qs?.module_deleted||qs?.lesson_created||qs?.lesson_saved||qs?.lesson_deleted||qs?.material_created||qs?.material_saved||qs?.material_deleted
 return <div className="page">
  <div className="section-head"><div><Link prefetch={false} href="/admin/programas" className="badge">← Voltar para conteúdos</Link><h3 style={{fontSize:30,marginTop:12}}>{program.title}</h3><p>{type.label} • {enrollment_count} matrícula(s) • {lessons.length} aula(s) • {materials.length} material(is)</p></div></div>
  {ok&&<div className="alert alert-success">Alterações salvas com sucesso.</div>}
  {qs?.error&&<div className="alert alert-error">{qs.error}</div>}

  <form action={updateProgram} className="card form-card admin-editor-form">
   <input type="hidden" name="program_id" value={program.id}/>
   <div className="section-head"><div><span className="eyebrow">Configuração principal</span><h3>Dados do conteúdo</h3></div><button className="btn btn-primary">Salvar conteúdo</button></div>
   <div className="grid grid-2">
    <div className="field"><label>Título *</label><input name="title" required defaultValue={program.title||''}/></div>
    <div className="field"><label>Slug *</label><input name="slug" required defaultValue={program.slug||''}/></div>
    <div className="field"><label>Tipo</label><select name="content_type" defaultValue={program.content_type||'course'}><option value="course">Curso</option><option value="mentoring">Mentoria</option><option value="immersion">Imersão</option><option value="training">Treinamento</option><option value="event">Evento</option><option value="community">Comunidade</option></select></div>
    <div className="field"><label>Status</label><select name="status" defaultValue={program.status||'draft'}><option value="draft">Rascunho</option><option value="published">Publicado</option><option value="coming_soon">Em breve</option><option value="archived">Arquivado</option></select></div>
    <div className="field"><label>Posição</label><input name="position" type="number" defaultValue={program.position??0}/></div>
    <div className="field checkbox-field"><label><input name="catalog_visible" type="checkbox" defaultChecked={program.catalog_visible!==false}/> Exibir capa na vitrine</label><small>Alunas sem acesso veem apenas a capa bloqueada.</small></div>
   </div>
   <div className="field"><label>Subtítulo</label><input name="subtitle" defaultValue={program.subtitle||''}/></div>
   <div className="field"><label>Descrição</label><textarea name="description" rows="5" defaultValue={program.description||''}/></div>
   <div className="field"><label>URL da capa</label><input name="cover_url" defaultValue={program.cover_url||''}/></div>
  </form>

  <section className="section">
   <div className="section-head"><div><h3>Módulos e aulas</h3><p>Organize a sequência didática e publique somente o que estiver pronto.</p></div></div>
   <form action={createModule} className="card form-card inline-create-form"><input type="hidden" name="program_id" value={program.id}/><div className="field"><label>Novo módulo</label><input name="title" required placeholder="Título do módulo"/></div><div className="field"><label>Posição</label><input name="position" type="number" defaultValue={modules.length+1}/></div><div className="field"><label>Status</label><select name="status" defaultValue="published"><option value="published">Publicado</option><option value="draft">Rascunho</option></select></div><button className="btn btn-primary">Adicionar módulo</button></form>
   <div className="admin-module-list">
    {modules.map(module=><div className="card admin-module-card" key={module.id}>
      <form action={updateModule} className="admin-module-head"><input type="hidden" name="program_id" value={program.id}/><input type="hidden" name="module_id" value={module.id}/><div className="field"><label>Título</label><input name="title" defaultValue={module.title}/></div><div className="field"><label>Posição</label><input name="position" type="number" defaultValue={module.position??0}/></div><div className="field"><label>Status</label><select name="status" defaultValue={module.status}><option value="published">Publicado</option><option value="draft">Rascunho</option></select></div><div className="field module-description"><label>Descrição</label><input name="description" defaultValue={module.description||''}/></div><button className="btn btn-secondary btn-small">Salvar módulo</button></form>
      <div className="admin-lesson-list">
       {(lessonsByModule.get(module.id)||[]).map(lesson=><details className="admin-editor-details" key={lesson.id}><summary><strong>{lesson.position}. {lesson.title}</strong><span>{childStatusLabel(lesson.status)} • {lesson.duration_seconds??0}s</span></summary><form action={updateLesson} className="form-card compact-editor"><input type="hidden" name="program_id" value={program.id}/><input type="hidden" name="lesson_id" value={lesson.id}/><div className="grid grid-2"><div className="field"><label>Título</label><input name="title" defaultValue={lesson.title}/></div><div className="field"><label>Módulo</label><select name="module_id" defaultValue={lesson.module_id}>{modules.map(m=><option key={m.id} value={m.id}>{m.title}</option>)}</select></div><div className="field"><label>Posição</label><input name="position" type="number" defaultValue={lesson.position??0}/></div><div className="field"><label>Status</label><select name="status" defaultValue={lesson.status}><option value="draft">Rascunho</option><option value="published">Publicado</option></select></div><div className="field"><label>Duração (segundos)</label><input name="duration_seconds" type="number" min="0" defaultValue={lesson.duration_seconds??0}/></div><div className="field"><label>Liberar em</label><input name="release_at" type="datetime-local" defaultValue={localDateTime(lesson.release_at)}/></div></div><div className="field"><label>Resumo</label><input name="summary" defaultValue={lesson.summary||''}/></div><div className="field"><label>Descrição</label><textarea name="description" rows="4" defaultValue={lesson.description||''}/></div><div className="grid grid-2"><div className="field"><label>Provedor de vídeo</label><input name="video_provider" defaultValue={lesson.video_provider||'external'}/></div><div className="field"><label>URL do vídeo</label><input name="video_url" defaultValue={lesson.video_url||''}/></div></div><div className="field"><label>URL do poster</label><input name="poster_url" defaultValue={lesson.poster_url||''}/></div><div className="actions"><button className="btn btn-primary">Salvar aula</button></div></form><form action={deleteLesson} className="danger-inline"><input type="hidden" name="program_id" value={program.id}/><input type="hidden" name="lesson_id" value={lesson.id}/><button className="btn btn-danger btn-small">Excluir aula</button></form></details>)}
       <details className="admin-editor-details create-details"><summary><strong>+ Adicionar aula neste módulo</strong></summary><form action={createLesson} className="form-card compact-editor"><input type="hidden" name="program_id" value={program.id}/><input type="hidden" name="module_id" value={module.id}/><div className="grid grid-2"><div className="field"><label>Título *</label><input name="title" required/></div><div className="field"><label>Posição</label><input name="position" type="number" defaultValue={(lessonsByModule.get(module.id)||[]).length+1}/></div><div className="field"><label>Status</label><select name="status" defaultValue="draft"><option value="draft">Rascunho</option><option value="published">Publicado</option></select></div><div className="field"><label>Duração (segundos)</label><input name="duration_seconds" type="number" min="0" defaultValue="0"/></div></div><div className="field"><label>Resumo</label><input name="summary"/></div><div className="field"><label>Descrição</label><textarea name="description" rows="4"/></div><div className="grid grid-2"><div className="field"><label>URL do vídeo</label><input name="video_url"/></div><div className="field"><label>URL do poster</label><input name="poster_url"/></div></div><button className="btn btn-primary">Criar aula</button></form></details>
      </div>
      {(lessonsByModule.get(module.id)||[]).length===0?<form action={deleteModule} className="danger-inline module-danger"><input type="hidden" name="program_id" value={program.id}/><input type="hidden" name="module_id" value={module.id}/><button className="btn btn-danger btn-small">Excluir módulo vazio</button></form>:<small className="muted" style={{display:'block',padding:'0 16px 14px'}}>Para excluir este módulo, mova ou exclua as aulas primeiro.</small>}
    </div>)}
    {!modules.length&&<div className="card empty">Nenhum módulo cadastrado.</div>}
   </div>
  </section>

  <section className="section">
   <div className="section-head"><div><h3>Materiais</h3><p>PDFs, planilhas, checklists e outros arquivos vinculados a este conteúdo.</p></div></div>
   <form action={createMaterial} className="card form-card inline-create-form material-create"><input type="hidden" name="program_id" value={program.id}/><div className="field"><label>Título</label><input name="title" required/></div><div className="field"><label>URL do arquivo</label><input name="file_url" required/></div><div className="field"><label>Tipo</label><input name="file_type" defaultValue="PDF"/></div><div className="field"><label>Status</label><select name="status" defaultValue="published"><option value="published">Publicado</option><option value="draft">Rascunho</option></select></div><button className="btn btn-primary">Adicionar material</button></form>
   <div className="admin-material-list">{materials.map(material=><details className="card admin-editor-details" key={material.id}><summary><strong>{material.title}</strong><span>{material.file_type} • {childStatusLabel(material.status)}</span></summary><form action={updateMaterial} className="form-card compact-editor"><input type="hidden" name="program_id" value={program.id}/><input type="hidden" name="material_id" value={material.id}/><div className="grid grid-2"><div className="field"><label>Título</label><input name="title" defaultValue={material.title}/></div><div className="field"><label>URL do arquivo</label><input name="file_url" defaultValue={material.file_url}/></div><div className="field"><label>Tipo</label><input name="file_type" defaultValue={material.file_type||'PDF'}/></div><div className="field"><label>Status</label><select name="status" defaultValue={material.status}><option value="published">Publicado</option><option value="draft">Rascunho</option></select></div><div className="field"><label>Módulo (opcional)</label><select name="module_id" defaultValue={material.module_id||''}><option value="">Sem vínculo</option>{modules.map(m=><option key={m.id} value={m.id}>{m.title}</option>)}</select></div><div className="field"><label>Aula (opcional)</label><select name="lesson_id" defaultValue={material.lesson_id||''}><option value="">Sem vínculo</option>{lessons.map(l=><option key={l.id} value={l.id}>{l.title}</option>)}</select></div></div><div className="field"><label>Descrição</label><textarea name="description" rows="3" defaultValue={material.description||''}/></div><button className="btn btn-primary">Salvar material</button></form><form action={deleteMaterial} className="danger-inline"><input type="hidden" name="program_id" value={program.id}/><input type="hidden" name="material_id" value={material.id}/><button className="btn btn-danger btn-small">Excluir material</button></form></details>)}{!materials.length&&<div className="card empty">Nenhum material cadastrado.</div>}</div>
  </section>

  <section className="section danger-zone"><div className="card form-card danger-card"><span className="eyebrow danger-eyebrow">Zona de segurança</span><h3 style={{color:'#781f27'}}>Excluir conteúdo</h3><p className="muted">A exclusão só é permitida quando não existe nenhuma matrícula vinculada. Isso evita apagar acessos e progresso por engano.</p><form action={deleteProgram}><input type="hidden" name="program_id" value={program.id}/><button className="btn btn-danger" disabled={enrollment_count>0}>Excluir conteúdo</button>{enrollment_count>0&&<small style={{display:'block',marginTop:8}}>Há {enrollment_count} matrícula(s). Remova ou transfira os acessos antes.</small>}</form></div></section>
 </div>
}
